paises_index:
   path: /
   controller: App\Controller\Api\PaisesController::index
   methods: [GET, POST, PUT, DELETE]


# paises_agregar:
#    path: /pais/agregar
#    controller: App\Controller\PaisesController::agregar


# paises_modificar:
#    path: /pais/modificar/{pais}
#    controller: App\Controller\PaisesController::modificar